name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dmmusil
          npm install
          npm run ng -- deploy --branch=main --no-silent --name "Dylan Musil" --email "dmmusil@ncsu.edu"
